### ISSUE TITLE
unknownAtRules error for tailwind v4

### ISSUE THREAD

**Issue by Alvi24** [biomejs/biome#7223]
# Update

For those of you finding this via search: The fix has already been merged to our `next` branch, and it'll be in your hands when the next minor (2.3) is released.

-- @dyc3

---

### Environment information

```bash
CLI:
  Version:                      2.2.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  BIOME_THREADS:                unset
  NO_COLOR:                     unset
  TERM:                         xterm-256color
  JS_RUNTIME_VERSION:           v22.18.0
  JS_RUNTIME_NAME:              node
  NODE_PACKAGE_MANAGER:         bun/1.2.20

Biome Configuration:
  Status:                       Loaded successfully
  Path:                         biome.json
  Formatter enabled:            true
  Linter enabled:               true
  Assist enabled:               true
  VCS enabled:                  false

Linter:
  JavaScript enabled:           unset
  JSON enabled:                 unset
  CSS enabled:                  unset
  GraphQL enabled:              unset
  Recommended:                  true
  Enabled rules:
    a11y/noAccessKey
    a11y/noAriaHiddenOnFocusable
    a11y/noAriaUnsupportedElements
    a11y/noAutofocus
    a11y/noDistractingElements
    a11y/noHeaderScope
    a11y/noInteractiveElementToNoninteractiveRole
    a11y/noLabelWithoutControl
    a11y/noNoninteractiveElementToInteractiveRole
    a11y/noNoninteractiveTabindex
    a11y/noPositiveTabindex
    a11y/noRedundantAlt
    a11y/noRedundantRoles
    a11y/noStaticElementInteractions
    a11y/useAltText
    a11y/useAnchorContent
    a11y/useAriaActivedescendantWithTabindex
    a11y/useAriaPropsForRole
    a11y/useAriaPropsSupportedByRole
    a11y/useButtonType
    a11y/useFocusableInteractive
    a11y/useGenericFontNames
    a11y/useHeadingContent
    a11y/useHtmlLang
    a11y/useIframeTitle
    a11y/useMediaCaption
    a11y/useSemanticElements
    a11y/useValidAnchor
    a11y/useValidAriaProps
    a11y/useValidAriaRole
    a11y/useValidAriaValues
    a11y/useValidAutocomplete
    a11y/useValidLang
    complexity/noAdjacentSpacesInRegex
    complexity/noArguments
    complexity/noBannedTypes
    complexity/noCommaOperator
    complexity/noEmptyTypeParameters
    complexity/noExtraBooleanCast
    complexity/noFlatMapIdentity
    complexity/noImportantStyles
    complexity/noStaticOnlyClass
    complexity/noThisInStatic
    complexity/noUselessCatch
    complexity/noUselessConstructor
    complexity/noUselessContinue
    complexity/noUselessEmptyExport
    complexity/noUselessEscapeInRegex
    complexity/noUselessFragments
    complexity/noUselessLabel
    complexity/noUselessLoneBlockStatements
    complexity/noUselessRename
    complexity/noUselessStringRaw
    complexity/noUselessSwitchCase
    complexity/noUselessTernary
    complexity/noUselessThisAlias
    complexity/noUselessTypeConstraint
    complexity/noUselessUndefinedInitialization
    complexity/useArrowFunction
    complexity/useDateNow
    complexity/useFlatMap
    complexity/useIndexOf
    complexity/useLiteralKeys
    complexity/useNumericLiterals
    complexity/useOptionalChain
    complexity/useRegexLiterals
    complexity/useSimpleNumberKeys
    correctness/noChildrenProp
    correctness/noConstAssign
    correctness/noConstantCondition
    correctness/noConstantMathMinMaxClamp
    correctness/noConstructorReturn
    correctness/noEmptyCharacterClassInRegex
    correctness/noEmptyPattern
    correctness/noGlobalObjectCalls
    correctness/noInnerDeclarations
    correctness/noInvalidBuiltinInstantiation
    correctness/noInvalidConstructorSuper
    correctness/noInvalidDirectionInLinearGradient
    correctness/noInvalidGridAreas
    correctness/noInvalidPositionAtImportRule
    correctness/noInvalidUseBeforeDeclaration
    correctness/noMissingVarFunction
    correctness/noNonoctalDecimalEscape
    correctness/noPrecisionLoss
    correctness/noSelfAssign
    correctness/noSetterReturn
    correctness/noStringCaseMismatch
    correctness/noSwitchDeclarations
    correctness/noUnknownFunction
    correctness/noUnknownMediaFeatureName
    correctness/noUnknownProperty
    correctness/noUnknownPseudoClass
    correctness/noUnknownPseudoElement
    correctness/noUnknownTypeSelector
    correctness/noUnknownUnit
    correctness/noUnmatchableAnbSelector
    correctness/noUnreachable
    correctness/noUnreachableSuper
    correctness/noUnsafeFinally
    correctness/noUnsafeOptionalChaining
    correctness/noUnusedFunctionParameters
    correctness/noUnusedImports
    correctness/noUnusedLabels
    correctness/noUnusedPrivateClassMembers
    correctness/noUnusedVariables
    correctness/noVoidElementsWithChildren
    correctness/noVoidTypeReturn
    correctness/useGraphqlNamedOperations
    correctness/useIsNan
    correctness/useParseIntRadix
    correctness/useValidForDirection
    correctness/useValidTypeof
    correctness/useYield
    nursery/useSortedClasses
    performance/noAccumulatingSpread
    performance/noDynamicNamespaceImportAccess
    security/noBlankTarget
    security/noDangerouslySetInnerHtml
    security/noDangerouslySetInnerHtmlWithChildren
    security/noGlobalEval
    style/noDescendingSpecificity
    style/noInferrableTypes
    style/noNonNullAssertion
    style/noParameterAssign
    style/noUnusedTemplateLiteral
    style/noUselessElse
    style/useArrayLiterals
    style/useAsConstAssertion
    style/useConst
    style/useDefaultParameterLast
    style/useDeprecatedReason
    style/useEnumInitializers
    style/useExponentiationOperator
    style/useExportType
    style/useImportType
    style/useLiteralEnumMembers
    style/useNodejsImportProtocol
    style/useNumberNamespace
    style/useSelfClosingElements
    style/useShorthandFunctionType
    style/useSingleVarDeclarator
    style/useTemplate
    suspicious/noApproximativeNumericConstant
    suspicious/noArrayIndexKey
    suspicious/noAssignInExpressions
    suspicious/noAsyncPromiseExecutor
    suspicious/noBiomeFirstException
    suspicious/noCatchAssign
    suspicious/noClassAssign
    suspicious/noCommentText
    suspicious/noCompareNegZero
    suspicious/noConfusingLabels
    suspicious/noConfusingVoidType
    suspicious/noConstEnum
    suspicious/noControlCharactersInRegex
    suspicious/noDebugger
    suspicious/noDocumentCookie
    suspicious/noDoubleEquals
    suspicious/noDuplicateAtImportRules
    suspicious/noDuplicateCase
    suspicious/noDuplicateClassMembers
    suspicious/noDuplicateCustomProperties
    suspicious/noDuplicateElseIf
    suspicious/noDuplicateFields
    suspicious/noDuplicateFontNames
    suspicious/noDuplicateJsxProps
    suspicious/noDuplicateObjectKeys
    suspicious/noDuplicateParameters
    suspicious/noDuplicateProperties
    suspicious/noDuplicateSelectorsKeyframeBlock
    suspicious/noEmptyBlock
    suspicious/noEmptyInterface
    suspicious/noExplicitAny
    suspicious/noExtraNonNullAssertion
    suspicious/noFallthroughSwitchClause
    suspicious/noFunctionAssign
    suspicious/noGlobalAssign
    suspicious/noGlobalIsFinite
    suspicious/noGlobalIsNan
    suspicious/noImplicitAnyLet
    suspicious/noImportAssign
    suspicious/noImportantInKeyframe
    suspicious/noIrregularWhitespace
    suspicious/noLabelVar
    suspicious/noMisleadingCharacterClass
    suspicious/noMisleadingInstantiator
    suspicious/noMisrefactoredShorthandAssign
    suspicious/noOctalEscape
    suspicious/noPrototypeBuiltins
    suspicious/noQuickfixBiome
    suspicious/noRedeclare
    suspicious/noRedundantUseStrict
    suspicious/noSelfCompare
    suspicious/noShadowRestrictedNames
    suspicious/noShorthandPropertyOverrides
    suspicious/noSparseArray
    suspicious/noSuspiciousSemicolonInJsx
    suspicious/noTemplateCurlyInString
    suspicious/noThenProperty
    suspicious/noTsIgnore
    suspicious/noUnknownAtRules
    suspicious/noUnsafeDeclarationMerging
    suspicious/noUnsafeNegation
    suspicious/noUselessEscapeInString
    suspicious/noUselessRegexBackrefs
    suspicious/noWith
    suspicious/useAdjacentOverloadSignatures
    suspicious/useBiomeIgnoreFolder
    suspicious/useDefaultSwitchClauseLast
    suspicious/useGetterReturn
    suspicious/useGoogleFontDisplay
    suspicious/useIsArray
    suspicious/useIterableCallbackReturn
    suspicious/useNamespaceKeyword
```

### Rule name

noUnknownAtRules

### Playground link

basic global.css tailwind config

### Expected result

unknownAtRules (Unknown at rule @theme) should not be thrown for tailwind v4 rules (@theme,@custom-variant,@variant)

### Code of Conduct

- [x] I agree to follow Biome's Code of Conduct

**Comment by dyc3** [comment]
Already have a PR in the pipeline to fix this #7164 :)

**Comment by hqw567** [comment]
The `unknownAtRules` rule should exclude Tailwind CSS-specific directives. At the very least, there should be a configuration option to exclude them, or the rule should automatically detect if the project is using Tailwind CSS and exclude them accordingly.

**Comment by dyc3** [comment]
When that PR is landed, you would enable tailwind directives for the css parser, and then you wouldn't get diagnostics for it.

But yes, the ideal scenario is "no configuration required". We have domains for lint rules that auto enable when we detect dependencies, but AFAIK that logic doesn't currently apply to parsing.

**Comment by ematipico** [comment]
@dyc3 should we close https://github.com/biomejs/biome/discussions/3195 in favour of a proper issue, so users can subscribe?

**Comment by dyc3** [comment]
Sure, makes sense to me

Update: it seems to me that people are finding this issue easily. So lets treat this issue as the tracking issue.

**Comment by damianobarbati** [comment]
will this pr also solve the following?
```sh
services/ui/src/style.css:17:2 lint/suspicious/noUnknownAtRules ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unexpected unknown at-rule: theme

    15 │ }
    16 │
  > 17 │ @theme {
       │  ^^^^^
    18 │   --font-display: "Montserrat", sans-serif;
    19 │

  ℹ theme is not a standard CSS at-rule, which may lead to unexpected styling results or failure to interpret the styles as intended.

  ℹ See MDN web docs for a known list of at-rules.

  ℹ To fix this issue, consider removing the unknown at-rule.
```

**Comment by dyc3** [comment]
Yes

**Comment by bgub** [comment]
It seems like the PR has been merged? When will it be released?

**Comment by dyc3** [comment]
When we release the next minor (2.3). We don't have a ETA for that.

**Comment by bgub** [comment]
@dyc3 is there any chance you could release a patch release before then?

In the latest release of Next.js we added Biome as an option for our starter template, but it's throwing errors when used with Tailwind 😅 

Thanks for the prompt fix and reply!

**Comment by dyc3** [comment]
It won't be in the next patch, because it's a minor level change. There's also a followup PR #7241 that is likely necessary. I'll see about doing a preview release so you can try it out.

**Comment by ematipico** [comment]
Now that I think about it, this requires updating the lint rule too, and make those at rules valid only when the parsing option is enabled

**Comment by kkhys** [comment]
As a temporary workaround, you can disable files that use unknownAtRules. This will likely be improved in the next release, so you can delete this rule at that time.

```json
{
  // ...
  "overrides": [
    {
    // Files using unknownAtRules
      "includes": ["src/styles/global.css"],
      "linter": {
        "enabled": false
      }
    }
  ]
}
```

**Comment by dyc3** [comment]
I've just published a new preview release with this feature. Note that we don't recommend using preview releases in production. You can install it with:

```bash
npm i https://pkg.pr.new/@biomejs/biome@72a8b02
```

You can enable the parser option with this configuration:

```json
{
  "css": {
    "parser": {
      "tailwindDirectives": true
    }
  }
}
```

**Comment by dyc3** [comment]
>  this requires updating the lint rule too

@ematipico I've thought about it a little bit and actually, I don't think the `noUnknownAtRules` rule needs to be updated at all. With this feature, we now emit parse diagnostics when we encounter tailwind syntax. So now, people will encounter the parser diag, which directs them to update their config, and linting doesn't end up happening at all.

**Before**: https://biomejs.dev/playground/?code=QABjAHUAcwB0AG8AbQAtAHYAYQByAGkAYQBuAHQAIABkAGEAcgBrACAAKAAmADoAaQBzACgALgBkAGEAcgBrACAAKgApACkAOwA%3D&language=css

```
/main.css:1:2 [lint/suspicious/noUnknownAtRules](https://biomejs.dev/linter/rules/no-unknown-at-rules) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Unexpected unknown at-rule: custom-variant 
  
  > 1 │ @custom-variant dark (&:is(.dark *));
      │  ^^^^^^^^^^^^^^
  
  ℹ custom-variant is not a standard CSS at-rule, which may lead to unexpected styling results or failure to interpret the styles as intended.
  
  ℹ See [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) for a known list of at-rules.
  
  ℹ To fix this issue, consider removing the unknown at-rule.
```

**After**: https://next.biomejs.dev/playground/?code=QABjAHUAcwB0AG8AbQAtAHYAYQByAGkAYQBuAHQAIABkAGEAcgBrACAAKAAmADoAaQBzACgALgBkAGEAcgBrACAAKgApACkAOwA%3D&language=css

```
main.css:1:2 parse ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Tailwind-specific syntax is disabled.
  
  > 1 │ @custom-variant dark (&:is(.dark *));
      │  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  ℹ Enable `tailwindDirectives` in the css parser options, or remove this if you are not using Tailwind CSS.
```

**Comment by tomdai** [comment]
Thanks for the great work! 

Just tried out the preview release `https://pkg.pr.new/@biomejs/biome@0d4661f` and found a issue:

In this utility at-rule:

```css
@utility border-overlay-* {
  position: relative;

  &::after {
    position: absolute;
    inset: 0;
    pointer-events: none;
    content: "";
    border-radius: inherit;
    border-width: --value(integer)px;
    border-width: --value([*]);
    @apply border-separator;
  }
}
```

The line `&::after {` causes a parsing error:

```
Expected a declaration item but instead found '&::after {
```

**Comment by dyc3** [comment]
Thank you @tomdai ! It's an easy fix. Should have another preview for you to try soon.

**Comment by dyc3** [comment]
I've just put out a new preview (and updated my previous comment):

```
npm i https://pkg.pr.new/@biomejs/biome@72a8b02
```

**Comment by alexandretrotel** [comment]
Thanks for all your work on this! Do you have an idea of when it might be released?

**Comment by dyc3** [comment]
@alexandretrotel See above: https://github.com/biomejs/biome/issues/7223#issuecomment-3215453777

**Comment by Geezgus** [comment]
I think instead of having tailwind specific at-rules baked in, we should be able to configure at-rules, as other frameworks (such as tailwind) may come by, establishing their own at-rules, and (i believe) Biome.js should be agnostic to them.

**Comment by alexandretrotel** [comment]
I would rather go for a hybrid approach: since Tailwind is widely adopted, it makes sense to provide first-class support for its at-rules out of the box, while also keeping the system flexible enough to allow users to configure custom at-rules from other frameworks.

Not sure how often Tailwind’s at-rules change, but if it’s rare, handling them specifically makes sense.

**Comment by Sylvain303** [comment]
Reading https://biomejs.dev/linter/rules/no-unknown-at-rules/ I first though I could use some option from https://github.com/stylelint/stylelint/tree/main/lib/rules/at-rule-no-unknown (as it's mentioned in the doc)

> ## Summary
> [...]
> Sources:
>
>    Same as [stylelint/at-rule-no-unknown](https://github.com/stylelint/stylelint/blob/main/lib/rules/at-rule-no-unknown/README.md)

So I tried: ⚠️ doesn't work

```json
  "linter": { 
    "enabled": true, 
    "rules": { 
      "recommended": true, 
      "suspicious": { 
        "noUnknownAtRules": { 
          "level" : "error", 
          "options" : { "ignoreAtRules": ["apply"] } 
        } 
      } 
    } 
  },
```

So yes hybrid approach sounds good.

But may not worded in negative work  / config but positive:

```json
"AtRulesAllow": [ "apply", "tailwind", "etc." ]
```

**Comment by holtetx** [comment]
Any updates on this? Updating from `2.1.1` to `2.2.4` (latest as of today) still breaks. For `@apply` `@theme` etc we still see `Unknown at-rule ...` errors.

**Comment by dyc3** [comment]
@holtetx It'll be fixed in the next minor (2.3)

**Comment by awesomezao** [comment]
My temporary solution
```json
...
  "overrides": [
    {
      "includes": ["src/index.css"],
      "linter": {
        "rules": {
          "suspicious": {
            "noUnknownAtRules": "off"
          }
        }
      }
    }
  ]
...
```

**Comment by ematipico** [comment]
Closing as completed by https://github.com/biomejs/biome/pull/7164

The fix will be available in v2.3

**Comment by PaulRBerg** [comment]
For anyone stumbling upon this thread from Google - after you upgrade to v2.3, you also have to enable `tailwindDirectives` for the CSS parser, like so:

```json
{
  "css": {
    "parser": {
      "tailwindDirectives": true
    }
  }
}
```

**Comment by jjlinares** [comment]
> For anyone stumbling upon this thread from Google - after you upgrade to v2.3, you also have to enable `tailwindDirectives` for the CSS parser, like so:
> 
> {
>   "css": {
>     "parser": {
>       "tailwindDirectives": true
>     }
>   }
> }

I have biome 2.3.2 installed and still get the warning for @custom-variant and @theme in my globals.css

**Comment by PaulRBerg** [comment]
@jjlinares me too: https://github.com/biomejs/biome/discussions/3195#discussioncomment-14838265

**Comment by zitooo** [comment]
Take a look here: https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-1979394

**Comment by mssngr** [comment]
EDIT: Looks like this is because I was using Tailwind v3, which wasn't supported in this fix.

I have biome 2.3.5 installed and still have the error, despite putting the directive. Makes no difference whether the directive is there or not.

<img width="601" height="617" alt="Image" src="https://github.com/user-attachments/assets/7496f301-9db8-443e-a061-47c6d6fe6f01" />

<br />
<br />

<img width="879" height="218" alt="Image" src="https://github.com/user-attachments/assets/543aed4d-a96b-41ba-b507-540a9b489c3e" />

**Comment by VesperQuartz** [comment]
Why is this stuff close if it's not fixed?

**Comment by codeplott** [comment]
This is still an issue. 
I have `tailwindDirectives` enabled, and it works in most cases, but I am still getting an error for the following case:

```css
@layer utilities {
  @variant xl { // <-- works fine
    .container {
      max-width: var(--breakpoint-xl);
    }
  }

  @variant 2xl { // <-- Error: Expected an identifier but instead found '2'.biome(parse)
    .container {
      max-width: var(--breakpoint-2xl);
    }
  }
}
```

**Comment by ematipico** [comment]
> Why is this stuff close if it's not fixed?

Because now we **parse** tailwind syntax, which means the fix involves the parser, not the linter. 

So, please don't comment on this issue, and **open a new issue**.

@sawden open a new issue
